[package]
name = "cobalt"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
futures = "0.3"
log = "0.4"
simple_logger = "2.1.0"
httparse = "1.7.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
bpaf = "0.4.3"
